//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public int turid { get; set; }
        public int userid { get; set; }
        public int sirketid { get; set; }
    
        public virtual departman departman { get; set; }
        public virtual detaylar detaylar { get; set; }
        public virtual user user { get; set; }
    }
}
