//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class geziEntities2 : DbContext
    {
        public geziEntities2()
            : base("name=geziEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<booking> booking { get; set; }
        public virtual DbSet<departman> departman { get; set; }
        public virtual DbSet<detaylar> detaylar { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
